# template development overrides

services:
  frontend:
    env_file:
      - ../.env.development
    environment:
      - NEXT_PUBLIC_ADMIN_NAME=${ADMIN_NAME:-Admin}
      - NEXT_PUBLIC_ADMIN_ROLE=${ADMIN_ROLE:-Administrator}
      - NEXT_PUBLIC_ADMIN_INITIALS=${ADMIN_INITIALS:-A}
      - NEXT_PUBLIC_ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - NEXT_PUBLIC_DEV_PASSWORD=${ADMIN_PASSWORD:-changeme}
      - NEXT_PUBLIC_PROJECT_DISPLAY_NAME=Template Project
      - NEXT_PUBLIC_PROJECT_DESCRIPTION=Project template development environment
      
  api:
    env_file:
      - ../.env.development
    volumes:
      - ../backend/.env:/app/.env:ro
